pipeline:
  build:
#    image: ecr.vip.ebayc3.com/newpro/cd:latest
    run: publish
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - date
      - echo "done"	
