apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-cd-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-cd
        release: canary
    spec:
      volumes:
        - name: node-cd-volume
          configMap:
            name: node-cd
      containers:
        - name: node-cd
          image: {{.Values.docker_image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
              name: http-port
          volumeMounts:
            - name: node-cd-volume
              mountPath: /node-cd
          env:
            - name: CONFIGPATH
              value: "/node-cd/foo"
            - name: PROP_DEMO
              value: ""
            - name: REPLICAS
              value: ""
            - name: CONSUL_HOST
              value: ""
            - name: CONSUL_PORT
              value: ""
            - name: ENV
              value: ""
            - name: REGION
              value: ""
            - name: CLUSTER
              value: ""
            - name: TAG
              value: ""
            - name: SHA
              value: ""
            - name: TIMESTAMP
              value: ""
