apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-cd
spec:
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: node-cd
        release: stable
    spec:
      volumes:
        - name: node-cd-volume
          configMap:
            name: node-cd
      containers:
        - name: node-cd
          image: {{.Values.docker_image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
              name: http-port
          volumeMounts:
            - name: node-cd-volume
              mountPath: /node-cd
          env:
            - name: CONFIGPATH
              value: "/node-cd/foo"
