apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-cd
spec:
  targetCPUUtilizationPercentage: 50
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: node-cd
